-- De wijnkaart van Au Vieux Port, overgenomen uit WineList_AVP_Website.pdf
-- (50 pagina's, 1 september 2026). 500 referenties.
--
-- De volgorde van de kaart is de volgorde van het huis: per kleur, dan per
-- land en streek, en binnen een producent zoals de sommelier ze zet. Die
-- volgorde staat in position, zodat de site de kaart toont zoals ze bedoeld is.

-- Dit vervangt de wijnen volledig. Bedoeld voor de eerste vulling.
truncate table wines;

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('sparkling', 'Perrier-Jouët', 'Grand Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 0.75, 110, 'Elegant style of champagne', 0),
  ('sparkling', 'Perrier-Jouët', 'Grand Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 1.5, 220, 'Elegant style of champagne', 1),
  ('sparkling', 'Perrier-Jouët', 'Blason Rosé | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 0.75, 130, 'Lively, generous and fresh', 2),
  ('sparkling', 'Perrier-Jouët', 'Blanc de Blancs', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], null, 0.75, 160, 'Bright, fresh and dynamic', 3),
  ('sparkling', 'Perrier-Jouët', 'Belle Epoque | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], 2014, 0.75, 350, 'Rare, elegant & harmonious', 4),
  ('sparkling', 'Perrier-Jouët', 'Belle Epoque Rosé', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], 2013, 0.75, 550, 'Delicate, elegant and complex', 5),
  ('sparkling', 'Perrier-Jouët', 'Belle Epoque Blanc de Blancs', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], 2012, 0.75, 675, 'The jewel of the collection', 6),
  ('sparkling', 'Billecart-Salmon', 'Le Réserve | Extra Brut', 'France', 'Champagne', null, ARRAY['Pinot Meunier','Pinot Noir','Chardonnay']::text[], null, 0.75, 130, 'Ageing 50 months on the lees', 7),
  ('sparkling', 'Billecart-Salmon', 'Le Rosé | Extra Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 0.75, 150, 'ageing for 36 months on the lees', 8),
  ('sparkling', 'Billecart-Salmon', 'Le Blanc de Blancs | Grand Cru | Extra Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], null, 0.75, 170, 'Ageing on the lees for 60 months', 9),
  ('sparkling', 'Billecart-Salmon', 'Cuvée Louis Salmon | Blanc de Blancs | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], 2008, 0.75, 350, 'From the best parcels of the Côte de Blancs | Pure and mineral', 10),
  ('sparkling', 'Billecart-Salmon', 'Cuvée Louis Salmon | Blanc de Blancs | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], 2012, 0.75, 350, 'From the best parcels of the Côte de Blancs | Pure and mineral', 11),
  ('sparkling', 'Billecart-Salmon', 'Cuvée Nicolas François | Extra Brut', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay (only Grand and Premier Crus)']::text[], 2012, 0.75, 350, '10% vinified in oak', 12),
  ('sparkling', 'Billecart-Salmon', 'Cuvée Elisabeth Salmon | Rosé | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir']::text[], 2012, 0.75, 350, '100% Grand & Premier Cru | Dosage 3,8 g/l', 13),
  ('sparkling', 'Ruinart', '"R" de Ruinart | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 0.75, 130, null, 14),
  ('sparkling', 'Ruinart', 'Blanc de Blancs | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], null, 0.75, 170, null, 15),
  ('sparkling', 'Pol Roger', 'Vintage Rosé | Brut', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay']::text[], 2015, 0.75, 150, null, 16),
  ('sparkling', 'Pol Roger', 'Blanc de Blancs | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], 2015, 0.75, 160, 'more than 6 years ageing on the lees', 17),
  ('sparkling', 'Louis Roederer', 'Brut Collection 245', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 0.75, 130, null, 18),
  ('sparkling', 'Louis Roederer', 'Brut Rosé', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir']::text[], 2017, 0.75, 160, null, 19),
  ('sparkling', 'Louis Roederer', 'Brut Blanc de Blancs', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], 2019, 0.75, 160, null, 20),
  ('sparkling', 'Louis Roederer', 'Cristal', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay']::text[], 2016, 0.75, 500, '6 years "sur lattes"', 21),
  ('sparkling', 'Bollinger', 'Special Cuvée | Brut', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay','Pinot Meunier']::text[], null, 0.75, 130, 'dosage 7-8 gr/l', 22),
  ('sparkling', 'Bollinger', 'Special Cuvée | Brut', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay','Pinot Meunier']::text[], null, 1.5, 270, 'dosage 7-8 gr/l', 23),
  ('sparkling', 'Bollinger', 'Grande Année | Brut', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay']::text[], 2012, 1.5, 650, 'dosage 8 gr/l', 24),
  ('sparkling', 'Bollinger', 'Grande Année Rosé | Brut', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay']::text[], 2012, 0.75, 400, 'dosage 8 gr/l', 25),
  ('sparkling', 'Bollinger', 'R.D. | Extra Brut', 'France', 'Champagne', null, ARRAY['Pinot Noir','Chardonnay']::text[], 2007, 0.75, 500, 'dosage 3 gr/l', 26),
  ('sparkling', 'Dom Pérignon', 'Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir']::text[], 2013, 0.75, 450, null, 27),
  ('sparkling', 'Dom Pérignon', 'Brut', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir']::text[], 2010, 1.5, 1100, null, 28),
  ('sparkling', 'Dom Pérignon', 'Rosé', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir']::text[], 2008, 0.75, 750, null, 29),
  ('sparkling', 'Krug', 'Grande Cuvée | 173ème édition', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 0.75, 450, 'Blend of 146 wines | Oldest wine from 2000', 30),
  ('sparkling', 'Krug', 'Rosé | 28ème édition', 'France', 'Champagne', null, ARRAY['Chardonnay','Pinot Noir','Pinot Meunier']::text[], null, 0.75, 675, 'Blend of 32 wines | Oldest wine from 2000', 31),
  ('sparkling', 'Pierre Peters', 'Cuvée de Réserve | Blanc de Blancs | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], null, 0.75, 140, 'long maturation on the lees', 32),
  ('sparkling', 'Pierre Peters', 'Réserve Oubliée | Grand Cru | Blanc de Blancs | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], null, 0.75, 220, 'long maturation on the lees', 33),
  ('sparkling', 'Pierre Peters', 'Les Chétillons - Le Mesnil | Grand Cru | Blanc de Blancs | Brut', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], 2018, 0.75, 395, 'long maturation on the lees', 34),
  ('sparkling', 'Agrapart', 'Atoma | Grand Cru', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], null, 0.75, 280, 'Multi-vintage, using a perpetual Grand Cru cuvée started in 2020', 35),
  ('sparkling', 'La Rogerie', 'Le Bourg /sud | Grand Cru | Réserve Perpetuelle', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], null, 0.75, 280, 'Aged in 228 & 400 L French oak | Reserve wine aged in 15hl foudre', 36),
  ('sparkling', 'La Rogerie', 'Heroïne', 'France', 'Champagne', null, ARRAY['Chardonnay']::text[], 2014, 0.75, 250, '90 months sur lie | Highly exclusive', 37),
  ('white', 'Clos d''Opleeuw', 'Chardonnay', 'Belgium', null, null, ARRAY['Chardonnay']::text[], 2023, 0.75, 140, 'Haspengouw | Ageing for 12 months on Belgian and French oak', 38),
  ('white', 'Clos d''Opleeuw', 'Chardonnay', 'Belgium', null, null, ARRAY['Chardonnay']::text[], 2024, 0.75, 140, 'Haspengouw | Ageing for 12 months on Belgian and French oak', 39),
  ('white', 'Clos d''Opleeuw', 'Chardonnay', 'Belgium', null, null, ARRAY['Chardonnay']::text[], 2024, 1.5, 300, 'Haspengouw | Ageing for 12 months on Belgian and French oak', 40),
  ('white', 'Clos d''Opleeuw', 'Pleistoceen', 'Belgium', null, null, ARRAY['Chardonnay']::text[], 2023, 0.75, 250, 'Haspengouw | Ageing for 12 months on Belgian and French oak', 41),
  ('white', 'Clos d''Opleeuw', 'Pleistoceen', 'Belgium', null, null, ARRAY['Chardonnay']::text[], 2024, 0.75, 250, 'Haspengouw | Ageing for 12 months on Belgian and French oak', 42),
  ('white', 'Domaine Trimbach', 'Pinot Blanc', 'France', 'Alsace', 'Alsace', ARRAY['Pinot Blanc']::text[], 2021, 0.75, 65, null, 43),
  ('white', 'Domaine Trimbach', 'Riesling', 'France', 'Alsace', 'Alsace', ARRAY['Riesling']::text[], 2022, 0.75, 75, null, 44),
  ('white', 'Domaine Albert Boxler', 'Pinot Gris Reserve', 'France', 'Alsace', 'Alsace', ARRAY['Pinot Gris']::text[], 2018, 0.75, 75, null, 45),
  ('white', 'Domaine Albert Boxler', 'Riesling', 'France', 'Alsace', 'Alsace', ARRAY['Riesling']::text[], 2021, 0.75, 90, null, 46),
  ('white', 'Domaine Albert Boxler', 'Riesling Grand Cru "Sommerberg"', 'France', 'Alsace', 'Alsace', ARRAY['Riesling']::text[], 2018, 0.75, 160, null, 47),
  ('white', 'Domaine Albert Boxler', 'Riesling Grand Cru "Sommerberg Eckberg"', 'France', 'Alsace', 'Alsace', ARRAY['Riesling']::text[], 2019, 0.75, 160, 'Very mineral', 48),
  ('white', 'Domaine Vincent Pinard', 'Sancerre "Florés"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2024, 0.75, 80, null, 49);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('white', 'Domaine J. Reverdy', 'Sancerre "La Reine Blanche"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2024, 0.75, 70, null, 50),
  ('white', 'Maison Pascal Jolivet', 'Sancerre', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2025, 0.75, 85, null, 51),
  ('white', 'Maison Pascal Jolivet', 'Pouilly-Fumé "Blanc Fumé"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 0.75, 85, '50% Calcareous soil - 30% Silex - 20% Calcareous clay', 52),
  ('white', 'Maison Pascal Jolivet', 'Pouilly-Fumé "Indigène"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2022, 0.75, 160, '100% Silex - Indigenous yeast - 12 months on the lees', 53),
  ('white', 'Domaine Michel Redde & Fils', 'Pouilly-Fumé "La Moynerie"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 0.75, 75, 'Vinification on stainless steel', 54),
  ('white', 'Domaine Michel Redde & Fils', 'Pouilly-Fumé "Barre à Mine"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2022, 0.75, 150, 'Vinification on stainless steel', 55),
  ('white', 'Domaine Michel Redde & Fils', 'Pouilly-Fumé "La Moynerie"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2021, 1.5, 150, 'Vinification on stainless steel', 56),
  ('white', 'Domaine Michel Redde & Fils', 'Pouilly-Fumé "Barre à Mine"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 1.5, 300, 'Vinification on stainless steel', 57),
  ('white', 'Domaine Didier Dagueneau', 'Pouilly-Fumé "Silex"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2019, 0.75, 250, 'Silex (flint) soil | Organic', 58),
  ('white', 'Clos Rougeard', 'Saumur Blanc "Brézé"', 'France', 'Loire', null, ARRAY['Chenin Blanc']::text[], 2020, 0.75, 395, 'Limestone soil | Crispy, complex and a very typical salinity', 59),
  ('white', 'Domaine Guiberteau', 'Saumur Blanc "Brézé"', 'France', 'Loire', null, ARRAY['Chenin Blanc']::text[], 2020, 0.75, 215, 'Bio', 60),
  ('white', 'Domaine de la Pépière', 'Muscadet Sèvre & Maine Sur Lie', 'France', 'Loire', null, ARRAY['Melon de Bourgogne']::text[], 2023, 0.75, 60, 'Vinification on stainless steel | Bio', 61),
  ('white', 'François Cotat', 'Sancerre "Les Culs de Beauje"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 0.75, 140, null, 62),
  ('white', 'François Cotat', 'Sancerre "Les Caillottes"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 0.75, 140, 'Kimmeridgian marl | No sulfites added during fermentation', 63),
  ('white', 'François Cotat', 'Sancerre "Les Caillottes"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2022, 0.75, 140, 'Kimmeridgian chalky soil | Aged in old barrels | Sauvignon at its best!', 64),
  ('white', 'François Cotat', 'Sancerre "Monts Damnés"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2022, 0.75, 160, 'Terres Blanches Kimmeridgian & Portlandien | Aged in old barrels', 65),
  ('white', 'François Cotat', 'Sancerre "Les Monts Damnés"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 0.75, 160, 'Terres Blanches Kimmeridgian & Portlandien', 66),
  ('white', 'François Cotat', 'Sancerre "Les Monts Damnés"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2022, 1.5, 320, 'Terres Blanches Kimmeridgian & Portlandien | No sulfites added during fermentation', 67),
  ('white', 'François Cotat', 'Sancerre "La Grande Côte"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2022, 0.75, 160, 'Terres Blanches Kimmeridgian | Aged in old barrels', 68),
  ('white', 'François Cotat', 'Sancerre "La Grande Côte"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 0.75, 160, 'Terres Blanches Kimmeridgian | No sulfites added during fermentation', 69),
  ('white', 'François Cotat', 'Sancerre "La Grande Côte"', 'France', 'Loire', null, ARRAY['Sauvignon Blanc']::text[], 2023, 1.5, 320, 'Terres Blanches Kimmeridgian | No sulfites added during fermentation', 70),
  ('white', 'Domaine Patrick Piuze', 'Chablis "Terroir de Chichée"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2023, 0.75, 95, 'Right bank of the Serein river', 71),
  ('white', 'Domaine Patrick Piuze', 'Chablis "Terroir de Fleys"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2023, 0.75, 95, 'Right bank of the Serein river', 72),
  ('white', 'Domaine Patrick Piuze', 'Chablis "Terroir de Fleys"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2024, 0.75, 95, 'Right bank of the Serein river', 73),
  ('white', 'Domaine Patrick Piuze', 'Chablis "Terroir de la Chapelle"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2024, 0.75, 95, 'Left bank of the Serein river', 74),
  ('white', 'Domaine Patrick Piuze', 'Chablis "La Grande Vallée"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2024, 0.75, 110, 'Left bank of the Serein river', 75),
  ('white', 'Domaine Patrick Piuze', 'Chablis 1er Cru "Les Forets"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2023, 0.75, 155, 'Left bank of the Serein river | Kimmeridgian soil | High minerality', 76),
  ('white', 'Domaine Patrick Piuze', 'Chablis 1er Cru "Butteaux"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2023, 0.75, 155, 'Left bank of the Serein river Kimmeridgian | High minerality', 77),
  ('white', 'Domaine Patrick Piuze', 'Chablis 1er Cru "Butteaux"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2024, 0.75, 155, 'Left bank of the Serein river Kimmeridgian | High minerality', 78),
  ('white', 'Domaine Patrick Piuze', 'Chablis 1er Cru "Les Séchets"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2023, 1.5, 315, 'Right bank | High portion of chalk | South-east exposure', 79),
  ('white', 'Domaine Patrick Piuze', 'Chablis Grand Cru "Bougros"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2024, 0.75, 220, 'Right bank | High portion of chalk | High minerality & complexity', 80),
  ('white', 'Samuel Billaud', 'Chablis Grand Cru "Blanchot"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2016, 0.75, 220, 'Right bank', 81),
  ('white', 'Samuel Billaud', 'Chablis Grand Cru "Vaudésir"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2017, 0.75, 220, 'Right bank', 82),
  ('white', 'Samuel Billaud', 'Chablis Grand Cru "Bougros"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2016, 0.75, 220, 'Right bank', 83),
  ('white', 'Samuel Billaud', 'Chablis Grand Cru "Les Clos"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2018, 0.75, 220, 'Right bank', 84),
  ('white', 'Vincent Dauvissat', 'Chablis 1er Cru "La Forest"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2019, 0.75, 215, null, 85),
  ('white', 'Vincent Dauvissat', 'Chablis 1er Cru "Vaillons"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2018, 0.75, 215, null, 86),
  ('white', 'Vincent Dauvissat', 'Chablis Grand Cru "Les Preuses"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2018, 0.75, 395, null, 87),
  ('white', 'François Raveneau', 'Chablis', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2020, 0.75, 210, null, 88),
  ('white', 'François Raveneau', 'Chablis 1er Cru "Montée de Tonnerre"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2020, 0.75, 290, null, 89),
  ('white', 'François Raveneau', 'Chablis 1er Cru "Montmains"', 'France', 'Burgundy', 'Chablis | Yonne', ARRAY['Chardonnay']::text[], 2018, 0.75, 290, null, 90),
  ('white', 'Domaine Bachelet-Monnot', 'Bourgogne Blanc', 'France', 'Burgundy', 'Regional', ARRAY['Chardonnay']::text[], 2022, 0.75, 95, null, 91),
  ('white', 'Domaines Leflaive', 'Bourgogne Blanc', 'France', 'Burgundy', 'Regional', ARRAY['Chardonnay']::text[], 2023, 0.75, 195, null, 92),
  ('white', 'Domaine Patrick Piuze', 'Bourgogne Blanc "Tonnerre"', 'France', 'Burgundy', 'Regional', ARRAY['Chardonnay']::text[], 2023, 0.75, 90, null, 93),
  ('white', 'Domaine Laurent Ponsot', 'Bourgogne Blanc', 'France', 'Burgundy', 'Regional', ARRAY['Chardonnay']::text[], 2020, 1.5, 220, null, 94),
  ('white', 'Domaine Comte Georges de Vogüé', 'Musigny Blanc', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Chardonnay']::text[], 2020, 0.75, 2100, null, 95),
  ('white', 'Domaine De Bellene', 'Savigny-Lès-Beaune', 'France', 'Burgundy', 'Côte d''Or | Savigny-lès-Beaune', ARRAY['Chardonnay']::text[], 2023, 0.75, 90, null, 96),
  ('white', 'Domaine Rollin', 'Pernand-Vergelesses "Les Cloux"', 'France', 'Burgundy', 'Côte d''Or | Pernand-Vergelesses | Aloxe-Corton', ARRAY['Chardonnay']::text[], 2023, 0.75, 100, null, 97),
  ('white', 'Domaine Dubreuil-Fontaine', 'Pernand-Vergelesses', 'France', 'Burgundy', 'Côte d''Or | Pernand-Vergelesses | Aloxe-Corton', ARRAY['Chardonnay']::text[], 2023, 0.75, 90, null, 98),
  ('white', 'Domaine Dubreuil-Fontaine', 'Corton-Charlemagne Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Pernand-Vergelesses | Aloxe-Corton', ARRAY['Chardonnay']::text[], 2021, 0.75, 225, null, 99);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('white', 'Domaine Rapet', 'Corton-Charlemagne Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Pernand-Vergelesses | Aloxe-Corton', ARRAY['Chardonnay']::text[], 2022, 0.75, 275, null, 100),
  ('white', 'Domaine Rapet', 'Corton-Charlemagne Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Pernand-Vergelesses | Aloxe-Corton', ARRAY['Chardonnay']::text[], 2019, 1.5, 550, null, 101),
  ('white', 'Domaine Henri Boillot', 'Corton-Charlemagne Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Pernand-Vergelesses | Aloxe-Corton', ARRAY['Chardonnay']::text[], 2020, 0.75, 550, null, 102),
  ('white', 'Domaine Maratray-Dubreuil', 'Ladoix 1er Cru "Les Gréchons"', 'France', 'Burgundy', 'Côte d''Or | Ladoix', ARRAY['Chardonnay']::text[], 2023, 0.75, 85, null, 103),
  ('white', 'Domaine Dupont-Fahn', 'Meursault "Les Clous"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2022, 0.75, 155, null, 104),
  ('white', 'Domaine Michel Bouzereau', 'Meursault "Les Grands Charrons"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2024, 0.75, 160, null, 105),
  ('white', 'Domaine Michel Bouzereau', 'Meursault 1er Cru "Charmes"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2023, 0.75, 295, null, 106),
  ('white', 'Domaine Jean Javiller', 'Meursault "Vieilles Vignes"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2023, 0.75, 130, null, 107),
  ('white', 'Domaine Albert Grivault', 'Meursault "Clos du Murger"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2022, 0.75, 180, null, 108),
  ('white', 'Domaine Albert Grivault', 'Meursault 1er Cru "Perrières"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2019, 0.75, 370, null, 109),
  ('white', 'Domaine Albert Grivault', 'Meursault 1er Cru "Clos de Perrières"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2018, 0.75, 485, null, 110),
  ('white', 'Domaine Bernard Millot', 'Meursault "La Barre"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2019, 0.75, 130, null, 111),
  ('white', 'Domaine Vincent Latour', 'Meursault "Grand Charron"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2022, 0.75, 130, null, 112),
  ('white', 'Domaine Vincent Latour', 'Meursault "Les Grands Charrons"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2020, 1.5, 280, null, 113),
  ('white', 'Domaine Vincent Latour', 'Meursault "Les Grands Charrons"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2019, 1.5, 280, null, 114),
  ('white', 'Domaine Vincent Latour', 'Meursault "Cuvée St-Jean"', 'France', 'Burgundy', 'Côte d''Or | Les Meursaults', ARRAY['Chardonnay']::text[], 2020, 1.5, 280, null, 115),
  ('white', 'Domaine Dupont-Fahn', 'Auxey-Duresses "Les Vireux"', 'France', 'Burgundy', 'Côte d''Or | Auxey-Duresses', ARRAY['Chardonnay']::text[], 2022, 0.75, 100, null, 116),
  ('white', 'Domaines Leflaive', 'Auxey-Duresses', 'France', 'Burgundy', 'Côte d''Or | Auxey-Duresses', ARRAY['Chardonnay']::text[], 2023, 0.75, 195, null, 117),
  ('white', 'Domaine Marc Colin', 'Saint-Aubin 1er Cru "En Remilly"', 'France', 'Burgundy', 'Côte d''Or | Les Saint-Aubins', ARRAY['Chardonnay']::text[], 2024, 0.75, 145, null, 118),
  ('white', 'Domaine Marc Colin', 'Saint-Aubin 1er Cru "En Créot"', 'France', 'Burgundy', 'Côte d''Or | Les Saint-Aubins', ARRAY['Chardonnay']::text[], 2024, 0.75, 135, null, 119),
  ('white', 'Domaine Larue', 'Saint-Aubin "Les Eduens"', 'France', 'Burgundy', 'Côte d''Or | Les Saint-Aubins', ARRAY['Chardonnay']::text[], 2022, 0.75, 110, null, 120),
  ('white', 'Domaine Joseph Colin', 'Saint-Aubin 1er Cru "Les Champlots"', 'France', 'Burgundy', 'Côte d''Or | Les Saint-Aubins', ARRAY['Chardonnay']::text[], 2023, 0.75, 135, null, 121),
  ('white', 'Domaine Bachelet-Monnot', 'Saint-Aubin 1er Cru "En Remilly"', 'France', 'Burgundy', 'Côte d''Or | Les Saint-Aubins', ARRAY['Chardonnay']::text[], 2022, 0.75, 240, null, 122),
  ('white', 'Domaine Bzikot', 'Puligny-Montrachet', 'France', 'Burgundy', 'Côte d''Or | Puligny-Montrachet', ARRAY['Chardonnay']::text[], 2023, 0.75, 175, null, 123),
  ('white', 'Domaine Joseph Colin', 'Puligny-Montrachet 1er Cru "La Garenne"', 'France', 'Burgundy', 'Côte d''Or | Puligny-Montrachet', ARRAY['Chardonnay']::text[], 2022, 0.75, 270, null, 124),
  ('white', 'Domaine Françoise et Denis Clair', 'Puligny-Montrachet 1er Cru "La Garenne"', 'France', 'Burgundy', 'Côte d''Or | Puligny-Montrachet', ARRAY['Chardonnay']::text[], 2023, 0.75, 165, null, 125),
  ('white', 'Domaine Bachelet-Monnot', 'Puligny-Montrachet', 'France', 'Burgundy', 'Côte d''Or | Puligny-Montrachet', ARRAY['Chardonnay']::text[], 2022, 0.75, 250, null, 126),
  ('white', 'Domaine Bachelet-Monnot', 'Puligny-Montrachet 1er Cru "Folatières"', 'France', 'Burgundy', 'Côte d''Or | Puligny-Montrachet', ARRAY['Chardonnay']::text[], 2022, 0.75, 450, null, 127),
  ('white', 'Domaine Bachelet-Monnot', 'Puligny-Montrachet 1er Cru "Referts"', 'France', 'Burgundy', 'Côte d''Or | Puligny-Montrachet', ARRAY['Chardonnay']::text[], 2022, 0.75, 410, null, 128),
  ('white', 'Domaine Bachelet-Monnot', 'Chassagne-Montrachet', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2022, 0.75, 235, null, 129),
  ('white', 'Domaine Vincent & François Jouard', 'Chassagne-Montrachet "Vieilles Vignes"', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2024, 0.75, 130, null, 130),
  ('white', 'Domaine Vincent & François Jouard', 'Chassagne-Montrachet 1er Cru "Morgeot - Fairendes"', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2023, 0.75, 160, null, 131),
  ('white', 'Domaine Vincent & François Jouard', 'Chassagne-Montrachet 1er Cru "Les Chenevottes"', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2023, 0.75, 160, null, 132),
  ('white', 'Domaine Vincent & François Jouard', 'Chassagne-Montrachet 1er Cru "Les Chaumées - Clos de la Truffière"', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2023, 0.75, 160, null, 133),
  ('white', 'Domaine Vincent & François Jouard', 'Chassagne-Montrachet 1er Cru "Maltroie"', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2023, 0.75, 160, null, 134),
  ('white', 'Domaine Michel Niellon', 'Chassagne-Montrachet', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2022, 0.75, 150, null, 135),
  ('white', 'Domaine Joseph Colin', 'Chassagne-Montrachet "Hereditas"', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2022, 0.75, 160, null, 136),
  ('white', 'Domaine Joseph Colin', 'Chassagne-Montrachet 1er Cru "En Cailleret"', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Chardonnay']::text[], 2023, 0.75, 190, null, 137),
  ('white', 'Domaine V& F Jouard', 'Bâtard-Montrachet Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Les Montrachets Grand Cru', ARRAY['Chardonnay']::text[], 2022, 0.75, 725, null, 138),
  ('white', 'Domaine Bachelet-Monnot', 'Bâtard-Montrachet Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Les Montrachets Grand Cru', ARRAY['Chardonnay']::text[], 2022, 0.75, 800, null, 139),
  ('white', 'Domaine De Bellene', 'Saint-Romain', 'France', 'Burgundy', 'Côte d''Or | Saint-Romain', ARRAY['Chardonnay']::text[], 2020, 0.75, 95, null, 140),
  ('white', 'Domaine Vincent Girardin', 'Saint-Romain', 'France', 'Burgundy', 'Côte d''Or | Saint-Romain', ARRAY['Chardonnay']::text[], 2021, 0.75, 110, null, 141),
  ('white', 'Saint-Romain', 'Alain Gras', 'France', 'Burgundy', 'Côte d''Or | Saint-Romain', ARRAY['Chardonnay']::text[], 2020, 0.75, 100, null, 142),
  ('white', 'Domaine Jacques Saumaize', 'Saint-Véran "En Crèches"', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2024, 0.75, 85, null, 143),
  ('white', 'Domaine Jacques Saumaize', 'Saint-Véran "Les Cras"', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2022, 0.75, 95, null, 144),
  ('white', 'Domaine Jacques Saumaize', 'Pouilly-Fuissé "Les Vieilles Vignes"', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2023, 0.75, 100, null, 145),
  ('white', 'Domaine Jacques Saumaize', 'Pouilly-Fuissé "Les Vieilles Vignes"', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2021, 1.5, 210, null, 146),
  ('white', 'Domaine Robert Dennogent', 'Mâcon-Villages "Les Sardines"', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2017, 1.5, 140, null, 147),
  ('white', 'Domaine Leflaive', 'Pouilly-Fuissé', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2023, 0.75, 185, null, 148),
  ('white', 'Domaine Leflaive', 'Mâcon-verzé', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2022, 0.75, 160, null, 149);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('white', 'Domaine Leflaive', 'Mâcon-verzé', 'France', 'Burgundy', 'Mâconnais', ARRAY['Chardonnay']::text[], 2023, 0.75, 160, null, 150),
  ('white', 'Domaine Vincent Dureuil-Janthial', 'Rully', 'France', 'Burgundy', 'Côte Chalonnaise', ARRAY['Chardonnay']::text[], 2023, 0.75, 90, null, 151),
  ('white', 'Domaine Claudie Jobard', 'Rully "Montagne la Folie"', 'France', 'Burgundy', 'Côte Chalonnaise', ARRAY['Chardonnay']::text[], 2023, 0.75, 100, 'Bio', 152),
  ('white', 'Domaine Claudie Jobard', 'Montagny 1er Cru "Madeleine"', 'France', 'Burgundy', 'Côte Chalonnaise', ARRAY['Chardonnay']::text[], 2022, 0.75, 100, null, 153),
  ('white', 'Domaine du Pélican (Marquis d''Angerville)', 'Chardonnay', 'France', 'Jura', null, ARRAY['Chardonnay']::text[], 2020, 0.75, 95, 'Biodynamic', 154),
  ('white', 'Domaine du Pélican', 'Chardonnay "Grands Curoulets"', 'France', 'Jura', null, ARRAY['Chardonnay']::text[], 2020, 0.75, 110, 'Biodynamic', 155),
  ('white', 'Chardonnay "Clos de la Tour Curon"', 'Bénédicte & Stéphane Tissot', 'France', 'Jura', null, ARRAY['Chardonnay']::text[], 2020, 0.75, 225, 'Calcarious soil | yield 12 hl/ha | Biodynamic', 156),
  ('white', 'Château Martet', 'Vignes de Compostelle', 'France', 'Bordeaux', null, ARRAY['Sémillon','Sauvignon Gris','Sauvignon Blanc','Muscadelle']::text[], 2021, 0.75, 70, 'Made by Mitjaville', 157),
  ('white', 'Château Carbonnieux', 'Pessac-Léognan Cru Classé', 'France', 'Bordeaux', null, ARRAY['Sauvignon Blanc','Sémillon']::text[], 2023, 0.75, 100, null, 158),
  ('white', 'Domaine Gauby', 'Calcinaires', 'France', 'Roussillon', null, ARRAY['Muscat','Chardonnay','Macabeo']::text[], 2019, 0.75, 65, 'Côtes Catalanes', 159),
  ('white', 'Domaine Muriel Giudicelli', 'Patrimonio Blanc', 'France', 'Corsica', null, ARRAY['Vermentino']::text[], 2024, 0.75, 110, 'Biodynamic | Fantastic balance', 160),
  ('white', 'Domaine Stéphane Ogier', 'Viognier de Rosine', 'France', 'Rhone Valley', null, ARRAY['Viognier']::text[], 2023, 0.75, 85, 'Collines Rhodaniennes', 161),
  ('white', 'Domaine Stéphane Ogier', 'Saint-Joseph "Passage"', 'France', 'Rhone Valley', null, ARRAY['Marsanne']::text[], 2022, 0.75, 95, 'Côtes du Rhône Septentrionales', 162),
  ('white', 'Domaine Combier', 'Crozes-Hermitage', 'France', 'Rhone Valley', null, ARRAY['Marsanne','Roussanne']::text[], 2023, 0.75, 75, 'Côtes du Rhône Septentrionales', 163),
  ('white', 'Domaine Combier', 'Crozes-Hermitage', 'France', 'Rhone Valley', null, ARRAY['Marsanne','Roussanne']::text[], 2021, 0.75, 160, 'Côtes du Rhône Septentrionales', 164),
  ('white', 'J.L. Chave Sélection', 'Crozes-Hermitage "Sybèle"', 'France', 'Rhone Valley', null, ARRAY['Marsanne','Roussanne']::text[], 2023, 0.75, 75, null, 165),
  ('white', 'J.L. Chave Sélection', 'Hermitage', 'France', 'Rhone Valley', null, ARRAY['Marsanne','Roussanne']::text[], 2021, 0.75, 530, null, 166),
  ('white', 'J.L. Chave Sélection', 'Hermitage', 'France', 'Rhone Valley', null, ARRAY['Marsanne','Roussanne']::text[], 2023, 0.75, 530, null, 167),
  ('white', 'Domaine Jeanne Gaillard', 'Marsanne', 'France', 'Rhone Valley', null, ARRAY['Marsanne']::text[], 2021, 0.75, 60, 'Collines Rhodaniennes', 168),
  ('white', 'Domaine George Vernay', 'Le Pied de Samson', 'France', 'Rhone Valley', null, ARRAY['Viognier']::text[], 2019, 0.75, 85, 'Collines Rhodaniennes', 169),
  ('white', 'Domaine George Vernay', 'Le Pied de Samson', 'France', 'Rhone Valley', null, ARRAY['Viognier']::text[], 2022, 0.75, 85, 'Collines Rhodaniennes', 170),
  ('white', 'Domaine George Vernay', 'Condrieu "Les Terrasses"', 'France', 'Rhone Valley', null, ARRAY['Viognier']::text[], 2018, 0.75, 160, 'Condrieu', 171),
  ('white', 'Domaine George Vernay', 'Condrieu "Les Chaillées de l''Enfer"', 'France', 'Rhone Valley', null, ARRAY['Viognier']::text[], 2020, 0.75, 220, 'Condrieu', 172),
  ('white', 'Domaine Isabel Ferrando', 'Châteauneuf-du-Pape Blanc', 'France', 'Rhone Valley', null, ARRAY['Clairette','Roussanne']::text[], 2021, 0.75, 195, 'Châteauneuf-du-Pape | Bio', 173),
  ('white', 'Domaine Clos des Pâpes', 'Châteauneuf-du-Pape Blanc', 'France', 'Rhone Valley', null, ARRAY['Grenache','Picpoul','Bourboulenc','Roussanne']::text[], 2023, 0.75, 170, 'Châteauneuf-du-Pape', 174),
  ('white', 'Domaine Château des Tours', 'Grenache Blanc', 'France', 'Rhone Valley', null, ARRAY['Grenache Blanc']::text[], 2019, 0.75, 120, 'Vaucluse', 175),
  ('white', 'Château Rayas', 'Châteauneuf-du-Pape Blanc', 'France', 'Rhone Valley', null, ARRAY['Grenache','Picpoul','Bourboulenc','Roussanne']::text[], 2013, 0.75, 1200, 'Châteauneuf-du-Pape', 176),
  ('white', 'Riesling "Pur Mineral"', 'Rudolf Fürst', 'Germany', null, null, ARRAY['Riesling']::text[], 2023, 0.75, 65, 'Baden', 177),
  ('white', 'Grauburgunder "Oberberger Bassgeige"', 'Franz Keller', 'Germany', null, null, ARRAY['Pinot Gris']::text[], 2020, 0.75, 55, 'Baden', 178),
  ('white', 'Chardonnay "Drei Dorfer"', 'Franz Keller', 'Germany', null, null, ARRAY['Chardonnay']::text[], 2021, 0.75, 120, 'Baden', 179),
  ('white', 'Chardonnay "Kirchberg" Grosses Gewächs', 'Franz Keller', 'Germany', null, null, ARRAY['Chardonnay']::text[], 2021, 0.75, 220, 'Baden | Aged for 12 months in 350 L oak barrels', 180),
  ('white', 'Saar Riesling', 'Van Volxem', 'Germany', null, null, ARRAY['Riesling']::text[], 2022, 0.75, 60, 'Saar', 181),
  ('white', 'Riesling "Schieferterrassen"', 'Heymann Löwenstein', 'Germany', null, null, ARRAY['Riesling']::text[], 2021, 0.75, 75, 'Mosel', 182),
  ('white', 'Weingut Battenfeld Spanier', 'Riesling "Kirchenstück" Grosse Lage', 'Germany', null, null, ARRAY['Riesling']::text[], 2019, 0.75, 110, 'Rheinhessen | Bio', 183),
  ('white', 'Grüner Veltliner "Durnstein"', 'Pichler - Krutzler', 'Austria', null, null, ARRAY['Grüner Veltliner']::text[], 2024, 0.75, 65, 'Wachau', 184),
  ('white', 'Sauvignon Blanc "Kalk & Kreide"', 'Tement', 'Austria', null, null, ARRAY['Sauvignon Blanc']::text[], 2025, 0.75, 75, 'Styria | Bio', 185),
  ('white', 'Sauvignon Blanc 1 Stk "Ried Grassnitzberg"', 'Tement', 'Austria', null, null, ARRAY['Sauvignon Blanc']::text[], 2021, 0.75, 110, 'Styria | Limestone soil | Bio | Premier Cru', 186),
  ('white', 'Branco Reserva', 'Morgadio de Calçada', 'Portugal', null, null, '{}', 2023, 0.75, 80, 'Douro | Rabigato - Codega de Larinha - Arinto & others', 187),
  ('white', 'Branco Reservado', 'Buçaco', 'Portugal', null, null, '{}', 2018, 0.75, 195, 'Bairadda | Encruzado - Bical - Maria Gomes | Cult Wine - Very Limited', 188),
  ('white', 'Nossa Calcario Branco', 'Filipa Pato & William Wouters', 'Portugal', null, null, ARRAY['Bical']::text[], 2022, 0.75, 85, 'Bairrada', 189),
  ('white', 'Branco', 'Mestre Daniel', 'Portugal', null, null, '{}', 2021, 0.75, 80, 'Alentejo | Antão Vaz - Perrum - Roupeiro | Wine made in amphora', 190),
  ('white', 'Granito Cru Branco', 'Luis Seabra', 'Portugal', null, null, ARRAY['Encruzado','Bical','Sercial']::text[], 2022, 0.75, 90, 'Dão | Aged in used barrels | Burgundy Style', 191),
  ('white', 'Xisto Cru Branco', 'Luis Seabra', 'Portugal', null, null, ARRAY['Rabigato','Viosinho Dozelino','Gouveio','Codega']::text[], 2024, 0.75, 115, 'Dão | Burgundy Style', 192),
  ('white', 'Louro', 'Raphael Palacios', 'Spain', 'Galicia', null, ARRAY['Godello','Treixadura']::text[], 2024, 0.75, 70, 'Valdeorras | Fermentation in barriques for 6 months', 193),
  ('white', 'Sorte O Soro', 'Raphael Palacios', 'Spain', 'Galicia', null, ARRAY['Godello']::text[], 2021, 0.75, 750, 'Valdeorras | Fermentation in French oak barrels (500 L) | Very limited', 194),
  ('white', 'Pazo Señorans', null, 'Spain', 'Galicia', null, ARRAY['Albariño']::text[], 2024, 0.75, 70, 'Rias Baixas', 195),
  ('white', 'Listán Blanco', 'Viñatigo', 'Spain', 'Canarias', null, ARRAY['Listán Blanco']::text[], 2024, 0.75, 70, 'Tenerife | Volcanic soil | Very fresh and mineral', 196),
  ('white', 'Gual', 'Viñatigo', 'Spain', 'Canarias', null, ARRAY['Gual']::text[], 2022, 0.75, 90, 'Tenerife | Volcanic soil | Almost extinguished grape variety from the Canarias', 197),
  ('white', 'Bodegas Altun', 'Rioja "Ana de Altun"', 'Spain', 'La Rioja', null, ARRAY['Viura','Malvasia']::text[], 2024, 0.75, 70, 'Rioja | Wonderful price / quality', 198),
  ('white', 'Rioja Blanco Reserva', 'Remirez de Ganuza', 'Spain', 'La Rioja', null, '{}', 2022, 0.75, 120, 'Rioja | Viura & Malvasía', 199);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('white', 'Bodegas Roda', 'Roda I Blanco', 'Spain', 'La Rioja', null, '{}', 2021, 0.75, 160, 'Rioja | Granacha Blanca - Viura & Malvasía Negra | Very limited', 200),
  ('white', 'Autòcton Blanc', 'Autòcton Celler', 'Spain', 'Catalunya', null, '{}', 2022, 0.75, 70, null, 201),
  ('white', 'Improvisació', 'Enric Soler', 'Spain', 'Catalunya', '100% Xarel.lo | 80% only stainless steel - 20% ageing on big casks', ARRAY['Xarel.lo']::text[], 2024, 0.75, 100, 'Penedes | Mineral - high acidity - no wood ageing', 202),
  ('white', 'Espenyalluchs', 'Enric Soler', 'Spain', 'Catalunya', '100% Xarel.lo | 80% only stainless steel - 20% ageing on big casks', ARRAY['Xarel.lo']::text[], 2023, 0.75, 130, 'Penedes | Ageing for 8 months on French oak', 203),
  ('white', 'Nun "Vinya dels Taus"', 'Enric Soler', 'Spain', 'Catalunya', '100% Xarel.lo | 80% only stainless steel - 20% ageing on big casks', ARRAY['Xarel.lo']::text[], 2024, 0.75, 185, 'Penedes | Best vineyard of the domain | Aged on French oak (Tonneliers from Burgundy)', 204),
  ('white', 'Ultreia', 'Raúl Pérez', 'Spain', 'Castilla y Leon', null, ARRAY['Godello']::text[], 2023, 0.75, 70, 'Bierzo', 205),
  ('white', 'Verdejo', 'José Pariente', 'Spain', 'Castilla y Leon', null, ARRAY['Verdejo']::text[], 2024, 0.75, 50, 'Rueda | Bushvines', 206),
  ('white', 'Sauvignon Blanc', 'José Pariente', 'Spain', 'Castilla y Leon', null, ARRAY['Sauvignon Blanc']::text[], 2024, 0.75, 55, 'Rueda', 207),
  ('white', 'Azienda Agricola Tamellini', 'Soave Classico "Le Bine de Costiola"', 'Italy', null, null, '{}', 2023, 0.75, 65, null, 208),
  ('white', 'Langhe Arneis', 'Ugo Lequio', 'Italy', 'Veneto', '100% Garganega | Fresh, crispy and mineral', '{}', 2023, 0.75, 70, null, 209),
  ('white', 'Etna Bianco', 'Viticoltori Benanti', 'Italy', 'Piedmont', '100% Arneis', '{}', 2024, 0.75, 65, null, 210),
  ('white', 'Etna Bianco "Contrada Rinazzo"', 'Viticoltori Benanti', 'Italy', 'Sicily', '100% Carricante', '{}', 2022, 0.75, 125, null, 211),
  ('white', 'Etna Bianco', 'Alta Mora', 'Italy', 'Sicily', '100% Carricante | East facing terrasses - 800 meter above sea level | Dry and mineral', '{}', 2024, 0.75, 60, null, 212),
  ('white', 'Cantina Terlan', 'Terlaner Cuvée', 'Italy', 'Sicily', '100% Carricante', ARRAY['Pinot Bianco','Chardonnay','Sauvignon Blanc']::text[], 2024, 0.75, 60, 'Alto Adige', 213),
  ('white', 'Casal di Serra', 'Umani Ronchi', 'Italy', 'Sicily', '100% Carricante', ARRAY['Verdicchio']::text[], 2023, 0.75, 65, 'Marken', 214),
  ('white', 'Cantina Terlan', 'Quarz Sauvignon', 'Italy', 'Sicily', '100% Carricante', ARRAY['Sauvignon Blanc']::text[], 2023, 0.75, 120, 'Alto Adige | Volcanic rock | 9 months on the lees | 50% wood aged', 215),
  ('white', 'Cantina Terlan', 'Primo Grande Cuvée', 'Italy', 'Sicily', '100% Carricante', ARRAY['Pinot Bianco','Chardonnay','Sauvignon Blanc']::text[], 2020, 0.75, 350, 'Alto Adige | Iconic!', 216),
  ('white', 'Fattoria San Lorenzo', 'Campo delle Ocche "Integrale"', 'Italy', 'Sicily', '100% Carricante', ARRAY['Verdicchio']::text[], 2015, 1.5, 160, 'Marche | Biodynamic | 48 months on the lees | Absolute top', 217),
  ('white', 'Sauvignon Blanc', 'Jayson by Pahlmeyer', 'USA', null, null, ARRAY['Sauvignon Blanc']::text[], 2024, 0.75, 125, 'Napa Valley', 218),
  ('white', 'Chardonnay', 'Jayson by Pahlmeyer', 'USA', null, null, ARRAY['Chardonnay']::text[], 2022, 0.75, 185, 'Napa Valley | Opulent and Complex', 219),
  ('white', 'Chardonnay', 'Pahlmeyer', 'USA', null, null, ARRAY['Chardonnay']::text[], 2022, 0.75, 285, 'Napa Valley | Old school Chardonnay | 100% New Oak', 220),
  ('white', 'Nauticus Sauvignon Blanc', 'Hasher Family Vines', 'South Africa', null, null, ARRAY['Sauvignon Blanc']::text[], 2024, 0.75, 65, 'Hemel-en-Aarde Valley | Fermentatie op inox, hout en beton', 221),
  ('white', 'Family Range Chardonnay', 'Hasher Family Vines', 'South Africa', null, null, ARRAY['Chardonnay']::text[], 2024, 0.75, 70, 'Hemel-en-Aarde Valley', 222),
  ('white', 'Marimist Chardonnay', 'Hasher Family Vines', 'South Africa', null, null, ARRAY['Chardonnay']::text[], 2023, 0.75, 95, 'Hemel-en-Aarde Valley | Top Burgundy style', 223),
  ('red', 'Weingut Rebholz', 'R', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2020, 0.75, 75, null, 224),
  ('red', 'Weingut Rebholz', 'Im Sonnenschein "Grösses Gewächs"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2016, 0.75, 185, null, 225),
  ('red', 'Weingut Knipser', 'Spätburgunder "Kalkmergel"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2019, 0.75, 80, null, 226),
  ('red', 'Weingut Knipser', 'Spätburgunder "Kalkmergel"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2019, 1.5, 160, 'Calcairious soil', 227),
  ('red', 'Weingut Rudolf Fürst', 'Burgstadt', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2021, 0.75, 80, null, 228),
  ('red', 'Weingut Rudolf Fürst', 'Hündsruck "Grösses Gewächs"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2014, 0.75, 325, null, 229),
  ('red', 'Weingut Rudolf Fürst', 'Hündsruck "Grösses Gewächs"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2021, 0.75, 325, null, 230),
  ('red', 'Weingut Jean Stodden', 'J', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2022, 0.75, 70, null, 231),
  ('red', 'Weingut Jean Stodden', 'Hardtberg "Grösses Gewächs"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2017, 0.75, 160, null, 232),
  ('red', 'Weingut Jean Stodden', 'Hardtberg "Grösses Gewächs"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2018, 0.75, 160, null, 233),
  ('red', 'Weingut Schlör', 'Schwarzriesling R', 'Germany', null, null, ARRAY['Pinot Meunier']::text[], 2020, 0.75, 75, null, 234),
  ('red', 'Weingut Dr. Heger', 'Spätburgunder "Mimus"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2019, 0.75, 95, null, 235),
  ('red', 'Weingut Dr. Heger', 'Ihringer Winklerberg "Grösses Gewächs"', 'Germany', null, null, ARRAY['Pinot Noir']::text[], 2018, 0.75, 165, null, 236),
  ('red', 'Domaine Grosbois', 'Chinon "Gabare"', 'France', 'Loire', null, ARRAY['Cabernet Franc']::text[], 2021, 0.75, 75, '11 months ageing in cement vats | Biological', 237),
  ('red', 'Domaine Pascal Jolivet', 'Sancerre', 'France', 'Loire', null, ARRAY['Pinot Noir']::text[], 2023, 0.75, 85, '8 months ageing on wooden vats', 238),
  ('red', 'Domaine Guiberteau', 'Saumur Rouge "Les Chapaudaises"', 'France', 'Loire', null, ARRAY['Cabernet Franc']::text[], 2021, 0.75, 160, 'Bio', 239),
  ('red', 'Clos Rougeard', 'Saumur-Champigny "Le Clos"', 'France', 'Loire', null, ARRAY['Cabernet Franc']::text[], 2020, 0.75, 275, 'Limestone soil | Crispy fruit', 240),
  ('red', 'Clos Rougeard', 'Saumur-Champigny "Les Poyeux"', 'France', 'Loire', null, ARRAY['Cabernet Franc']::text[], 2020, 0.75, 485, 'Clay and Aeolian sand soil | Finesse', 241),
  ('red', 'Clos Rougeard', 'Saumur-Champigny "Le Bourg"', 'France', 'Loire', null, ARRAY['Cabernet Franc']::text[], 2020, 0.75, 550, 'Limestone | Fresh fruit, dense and full bodied texture', 242),
  ('red', 'Domaine Coquard Loison Fleurot', 'Bourgogne Pinot Noir', 'France', 'Burgundy', 'Côte d''Or | Régionales | Hautes Côtes de Nuits', ARRAY['Pinot Noir']::text[], 2021, 0.75, 125, null, 243),
  ('red', 'Domaine Michel Noëllat', 'Hautes-Côtes de Nuits', 'France', 'Burgundy', 'Côte d''Or | Régionales | Hautes Côtes de Nuits', ARRAY['Pinot Noir']::text[], 2023, 0.75, 115, null, 244),
  ('red', 'Domaine Coquard Loison Fleurot', 'Gevrey-Chambertin', 'France', 'Burgundy', 'Côte d''Or | Gevrey-Chambertin', ARRAY['Pinot Noir']::text[], 2022, 0.75, 210, 'This domain is a hidden gem in Burgundy', 245),
  ('red', 'Domaine Maxime Cheurlin Noëllat', 'Gevrey-Chambertin "En Champs"', 'France', 'Burgundy', 'Côte d''Or | Gevrey-Chambertin', ARRAY['Pinot Noir']::text[], 2022, 0.75, 210, null, 246),
  ('red', 'Domaine Fréséric Esmonin', 'Gevrey-Chambertin "Les Jouises V. V."', 'France', 'Burgundy', 'Côte d''Or | Gevrey-Chambertin', ARRAY['Pinot Noir']::text[], 2021, 0.75, 145, null, 247),
  ('red', 'Domaine Fréséric Esmonin', 'Gevrey-Chambertin "Clos Prieur"', 'France', 'Burgundy', 'Côte d''Or | Gevrey-Chambertin', ARRAY['Pinot Noir']::text[], 2021, 0.75, 155, null, 248),
  ('red', 'Domaine Maxime Cheurlin Noëllat', 'Morey-Saint-Denis', 'France', 'Burgundy', 'Côte d''Or | Morey-Saint-Denis', ARRAY['Pinot Noir']::text[], 2022, 0.75, 180, null, 249);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('red', 'Domaine Forey Père & Fils', 'Morey-Saint-Denis', 'France', 'Burgundy', 'Côte d''Or | Morey-Saint-Denis', ARRAY['Pinot Noir']::text[], 2022, 0.75, 125, null, 250),
  ('red', 'Domaine Coquard Loison Fleurot', 'Morey-Saint-Denis', 'France', 'Burgundy', 'Côte d''Or | Morey-Saint-Denis', ARRAY['Pinot Noir']::text[], 2022, 0.75, 180, 'This domain is a hidden gem in Burgundy', 251),
  ('red', 'Domaine des Lambrays', 'Clos des Lambrays Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Morey-Saint-Denis', ARRAY['Pinot Noir']::text[], 2017, 0.75, 800, null, 252),
  ('red', 'Domaine des Lambrays', 'Clos des Lambrays Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Morey-Saint-Denis', ARRAY['Pinot Noir']::text[], 2018, 0.75, 850, null, 253),
  ('red', 'Domaine Maxime Cheurlin Noëllat', 'Chambolle-Musigny 1er Cru "Les Feusselottes"', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2022, 0.75, 425, 'This domain is a hidden gem in Burgundy', 254),
  ('red', 'Domaine Coquard Loison Fleurot', 'Chambolle-Musigny', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2022, 0.75, 220, 'This domain is a hidden gem in Burgundy', 255),
  ('red', 'Domaine Felettig', 'Chambolle-Musigny 1er Cru "Les Lavrottes"', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2017, 0.75, 220, null, 256),
  ('red', 'Domaine Felettig', 'Chambolle-Musigny 1er Cru "Aux Combottes"', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2022, 0.75, 220, null, 257),
  ('red', 'Domaine Sigaut', 'Chambolle-Musigny', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2022, 0.75, 150, null, 258),
  ('red', 'Domaine Sigaut', 'Chambolle-Musigny 1er Cru "Les Groseilles"', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2021, 0.75, 240, null, 259),
  ('red', 'Domaine Sigaut', 'Chambolle-Musigny 1er Cru "Les Noirots"', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2021, 0.75, 240, null, 260),
  ('red', 'Domaine Jean Grivot', 'Chambolle-Musigny "La Combe d''Orveaux"', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2020, 0.75, 240, null, 261),
  ('red', 'Domaine Thibault Ligier-Belair', 'Chambolle-Musigny "Les Fouchères"', 'France', 'Burgundy', 'Côte d''Or | Chambolle-Musigny', ARRAY['Pinot Noir']::text[], 2020, 0.75, 350, null, 262),
  ('red', 'Domaine Maxime Cheurlin Noëllat', 'Clos de Vougeot Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Vougeot', ARRAY['Pinot Noir']::text[], 2022, 0.75, 850, null, 263),
  ('red', 'Domaine Gros Frère et Soeur', 'Clos de Vougeot Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Vougeot', ARRAY['Pinot Noir']::text[], 2021, 0.75, 500, null, 264),
  ('red', 'Domaine Jean Grivot', 'Clos de Vougeot Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Vougeot', ARRAY['Pinot Noir']::text[], 2013, 0.75, 550, null, 265),
  ('red', 'Domaine Jean Grivot', 'Clos de Vougeot Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Vougeot', ARRAY['Pinot Noir']::text[], 2015, 0.75, 550, null, 266),
  ('red', 'Domaine Jean Grivot', 'Clos de Vougeot Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Vougeot', ARRAY['Pinot Noir']::text[], 2016, 0.75, 550, null, 267),
  ('red', 'Domaine Jean Grivot', 'Clos de Vougeot Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Vougeot', ARRAY['Pinot Noir']::text[], 2017, 0.75, 550, null, 268),
  ('red', 'Domaine Henri Boillot', 'Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2022, 0.75, 835, null, 269),
  ('red', 'Domaine Gros Frère et Soeur', 'Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2021, 0.75, 500, null, 270),
  ('red', 'Domaine Coquard Loison Fleurot', 'Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2020, 0.75, 550, 'This domain is a hidden gem in Burgundy', 271),
  ('red', 'Domaine Coquard Loison Fleurot', 'Grands Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2020, 0.75, 900, 'This domain is a hidden gem in Burgundy', 272),
  ('red', 'Domaine Jean Grivot', 'Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2013, 0.75, 600, null, 273),
  ('red', 'Domaine Jean Grivot', 'Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2018, 0.75, 700, null, 274),
  ('red', 'Domaine Emmanuel Rouget', 'Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2019, 0.75, 950, null, 275),
  ('red', 'Domaine Emmanuel Rouget', 'Echezeaux Grand Cru', 'France', 'Burgundy', 'Côte d''Or | Flagey-Echezeaux', ARRAY['Pinot Noir']::text[], 2018, 0.75, 975, null, 276),
  ('red', 'Domaine Georges Noëllat', 'Vosne-Romanée', 'France', 'Burgundy', 'Côte d''Or | Vosne-Romanée', ARRAY['Pinot Noir']::text[], 2022, 0.75, 290, null, 277),
  ('red', 'Domaine Emmanuel Rouget', 'Vosne-Romanée', 'France', 'Burgundy', 'Côte d''Or | Vosne-Romanée', ARRAY['Pinot Noir']::text[], 2020, 0.75, 380, null, 278),
  ('red', 'Domaine Michel Noëllat', 'Vosne-Romanée', 'France', 'Burgundy', 'Côte d''Or | Vosne-Romanée', ARRAY['Pinot Noir']::text[], 2023, 0.75, 180, null, 279),
  ('red', 'Domaine Michel Noëllat', 'Vosne-Romanée 1er Cru "Les Chaumes"', 'France', 'Burgundy', 'Côte d''Or | Vosne-Romanée', ARRAY['Pinot Noir']::text[], 2023, 0.75, 295, null, 280),
  ('red', 'Domaine Coquard Loison Fleurot', 'Vosne-Romanée', 'France', 'Burgundy', 'Côte d''Or | Vosne-Romanée', ARRAY['Pinot Noir']::text[], 2022, 0.75, 240, 'This domain is a hidden gem in Burgundy', 281),
  ('red', 'Domaine Coquard Loison Fleurot', 'Vosne-Romanée 1er Cru "', 'France', 'Burgundy', 'Côte d''Or | Vosne-Romanée', ARRAY['Pinot Noir']::text[], 2022, 0.75, 370, 'This domain is a hidden gem in Burgundy', 282),
  ('red', 'Domaine Jean Grivot', 'Vosne-Romanée "Les Bossières"', 'France', 'Burgundy', 'Côte d''Or | Vosne-Romanée', ARRAY['Pinot Noir']::text[], 2019, 0.75, 290, null, 283),
  ('red', 'Domaine Lécheneaut', 'Nuits-Saint-Georges 1er Cru "Clos du Corvée Pagets"', 'France', 'Burgundy', 'Côte d''Or | Nuits-Saint-Georges', ARRAY['Pinot Noir']::text[], 2021, 0.75, 190, null, 284),
  ('red', 'Domaine Michel Noëllat', 'Nuits-Saint-Georges "Aux Allots"', 'France', 'Burgundy', 'Côte d''Or | Nuits-Saint-Georges', ARRAY['Pinot Noir']::text[], 2023, 0.75, 150, null, 285),
  ('red', 'Domaine Maxime Cheurlin-Noëllat', 'Nuits-Saint-Georges', 'France', 'Burgundy', 'Côte d''Or | Nuits-Saint-Georges', ARRAY['Pinot Noir']::text[], 2020, 0.75, 180, null, 286),
  ('red', 'Domaine Emmanuel Rouget', 'Nuits-Saint-Georges', 'France', 'Burgundy', 'Côte d''Or | Nuits-Saint-Georges', ARRAY['Pinot Noir']::text[], 2020, 0.75, 375, null, 287),
  ('red', 'Domaine Sylvain Cathiard', 'Nuits-Saint-Georges 1er Cru "Aux Thorey"', 'France', 'Burgundy', 'Côte d''Or | Nuits-Saint-Georges', ARRAY['Pinot Noir']::text[], 2018, 0.75, 575, null, 288),
  ('red', 'Domaine Georges Noëllat', 'Corton Grand Cru "Les Hautes Mourottes"', 'France', 'Burgundy', 'Côte d''Or | Corton', ARRAY['Pinot Noir']::text[], 2022, 0.75, 550, null, 289),
  ('red', 'Domaine De Bellene', 'Saint-Romain "Vieilles Vignes"', 'France', 'Burgundy', 'Côte d''Or | Saint-Romain', ARRAY['Pinot Noir']::text[], 2022, 0.75, 95, null, 290),
  ('red', 'Domaine Antoine Jobard', 'Pommard 1er Cru "Epenots"', 'France', 'Burgundy', 'Côte d''Or | Pommard', ARRAY['Pinot Noir']::text[], 2020, 0.75, 360, null, 291),
  ('red', 'Domaine Bachelet-Monnot', 'Pommard "Les Chanlins"', 'France', 'Burgundy', 'Côte d''Or | Pommard', ARRAY['Pinot Noir']::text[], 2022, 0.75, 190, null, 292),
  ('red', 'Pommard "Vaumuriens"', 'François Raquillet', 'France', 'Burgundy', 'Côte d''Or | Pommard', ARRAY['Pinot Noir']::text[], 2021, 0.75, 130, null, 293),
  ('red', 'Domaine Henri Boillot', 'Volnay 1er Cru"Les Fremiets"', 'France', 'Burgundy', 'Côte d''Or | Volnay', ARRAY['Pinot Noir']::text[], 2022, 0.75, 270, null, 294),
  ('red', 'Domaine De Bellene', 'Volnay "Les Grand Poisots"', 'France', 'Burgundy', 'Côte d''Or | Volnay', ARRAY['Pinot Noir']::text[], 2018, 0.75, 135, null, 295),
  ('red', 'Saint-Aubin "Les Eduens"', 'Didier Larue', 'France', 'Burgundy', 'Côte d''Or | Saint-Aubin', ARRAY['Pinot Noir']::text[], 2023, 0.75, 90, null, 296),
  ('red', 'Chassagne-Montrachet "Vieilles Vignes"', 'Michel Niellon', 'France', 'Burgundy', 'Côte d''Or | Chassagne-Montrachet', ARRAY['Pinot Noir']::text[], 2023, 0.75, 120, null, 297),
  ('red', 'Santenay "Les Champs Claude"', 'Jean-Marc-Pillot', 'France', 'Burgundy', 'Côte d''Or | Santenay', ARRAY['Pinot Noir']::text[], 2022, 0.75, 95, null, 298),
  ('red', 'Domaine V. Dureuil-Janthial', 'Rully', 'France', 'Burgundy', 'Côte Chalonnaise | Rully', ARRAY['Pinot Noir']::text[], 2022, 0.75, 80, null, 299);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('red', 'Morgon "Légèrement Souffré"', 'Marcel Lapierre', 'France', 'Beaujolais', null, ARRAY['Gamay']::text[], 2024, 0.75, 75, null, 300),
  ('red', 'Morgon "Légèrement Souffré"', 'Marcel Lapierre', 'France', 'Beaujolais', null, ARRAY['Gamay']::text[], 2020, 1.5, 140, null, 301),
  ('red', 'Château Fleur de Lisse', 'Saint-Emilion Grand Cru', 'France', 'Bordeaux', 'Saint-Emilion', ARRAY['Merlot','Cabernet Franc']::text[], 2020, 0.75, 125, 'Biodynamic | The pinnacle of elegance', 302),
  ('red', 'Château Fleur de Lisse', 'Saint-Emilion Grand Cru', 'France', 'Bordeaux', 'Saint-Emilion', ARRAY['Merlot','Cabernet Franc']::text[], 2019, 1.5, 250, 'Biodynamic | The pinnacle of elegance', 303),
  ('red', 'Château Boutisse', 'Saint-Emilion Grand Cru Classé', 'France', 'Bordeaux', 'Saint-Emilion', ARRAY['Merlot','Cabernet Sauvignon','Cabernet Franc','Carmenère']::text[], 2019, 0.75, 80, null, 304),
  ('red', 'Château Peyreau', 'Saint-Emilion Grand Cru Classé', 'France', 'Bordeaux', 'Saint-Emilion', ARRAY['Merlot','Cabernet Sauvignon','Cabernet Franc']::text[], 2021, 0.75, 95, null, 305),
  ('red', 'Château Le Tertre Roteboeuf', 'Saint-Emilion Grand Cru Classé', 'France', 'Bordeaux', 'Saint-Emilion', ARRAY['Merlot','Cabernet Franc']::text[], 2011, 0.75, 550, 'François Mitjaville is an iconic winemaker', 306),
  ('red', 'Château Le Tertre Roteboeuf', 'Saint-Emilion Grand Cru Classé', 'France', 'Bordeaux', 'Saint-Emilion', ARRAY['Merlot','Cabernet Franc']::text[], 2007, 0.75, 400, 'François Mitjaville is an iconic winemaker', 307),
  ('red', 'Château Le Tertre Roteboeuf', 'Saint-Emilion Grand Cru Classé', 'France', 'Bordeaux', 'Saint-Emilion', ARRAY['Merlot','Cabernet Franc']::text[], 2016, 0.75, 600, 'François Mitjaville is an iconic winemaker', 308),
  ('red', 'Château L''Enclos', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc','Malbec']::text[], 2020, 0.75, 115, null, 309),
  ('red', 'Vieux Château Certan', 'La Gravette de Certan', 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc','Cabernet Sauvignon']::text[], 2018, 0.75, 195, null, 310),
  ('red', 'Vieux Château Certan', 'La Gravette de Certan', 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc','Cabernet Sauvignon']::text[], 2019, 0.75, 195, null, 311),
  ('red', 'Château La Grave - Trignant De Boisset', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc']::text[], 2016, 1.5, 265, null, 312),
  ('red', 'Château La Grave - Trignant De Boisset', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc']::text[], 2018, 0.75, 140, null, 313),
  ('red', 'Château Lafleur Gazin', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc']::text[], 2022, 0.75, 130, null, 314),
  ('red', 'Château Clinet', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc','Cabernet Sauvignon']::text[], 2015, 0.75, 280, null, 315),
  ('red', 'Château Clinet', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc','Cabernet Sauvignon']::text[], 2010, 0.75, 295, null, 316),
  ('red', 'Château L''Evangile', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc']::text[], 1995, 0.75, 750, null, 317),
  ('red', 'Château La Fleur Pétrus', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc']::text[], 1985, 0.75, 625, null, 318),
  ('red', 'Château La Conseillante', null, 'France', 'Bordeaux', 'Pomerol', ARRAY['Merlot','Cabernet Franc']::text[], 1990, 0.75, 750, null, 319),
  ('red', 'Château Perron', null, 'France', 'Bordeaux', 'Lalande de Pomerol', ARRAY['Merlot','Cabernet Franc','Cabernet Sauvignon']::text[], 2019, 0.75, 85, null, 320),
  ('red', 'Château La Prade - Nicolas Thienpont', null, 'France', 'Bordeaux', 'Francs Côtes de Bordeaux', ARRAY['Merlot','Cabernet Franc']::text[], 2019, 0.75, 75, null, 321),
  ('red', 'Château Martet', 'Les Hauts de Martet', 'France', 'Bordeaux', 'Francs Côtes de Bordeaux', ARRAY['Merlot','Cabernet Franc']::text[], 2019, 0.75, 75, 'Sainte-Foy-Côtes de Bordeaux | Made by Mitjaville', 322),
  ('red', 'Château Martet', 'Réserve de la Famille', 'France', 'Bordeaux', 'Francs Côtes de Bordeaux', ARRAY['Merlot']::text[], 2019, 0.75, 125, 'Sainte-Foy-Côtes de Bordeaux | Made by Mitjaville', 323),
  ('red', 'Château Cambon La Pelouse', 'Cru Bourgeois Exceptionel', 'France', 'Bordeaux', 'Médoc | Haut Médoc', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2018, 0.75, 95, null, 324),
  ('red', 'La Demoiselle de Sociando Mallet', null, 'France', 'Bordeaux', 'Médoc | Haut Médoc', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc']::text[], 2020, 0.75, 65, null, 325),
  ('red', 'Château La Lagune', '3ème Grand Cru Classé', 'France', 'Bordeaux', 'Médoc | Haut Médoc', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2019, 0.75, 140, null, 326),
  ('red', 'Château Clauzet', null, 'France', 'Bordeaux', 'St-Estephe', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot','Cabernet Franc']::text[], 2022, 0.75, 75, null, 327),
  ('red', 'Château Lafon Rochet', null, 'France', 'Bordeaux', 'St-Estephe', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2019, 0.75, 120, null, 328),
  ('red', 'Château Phélan Ségur', null, 'France', 'Bordeaux', 'St-Estephe', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2022, 0.75, 165, null, 329),
  ('red', 'La Dame de Montrose', null, 'France', 'Bordeaux', 'St-Estephe', ARRAY['Merlot','Cabernet Sauvignon']::text[], 2011, 0.75, 165, null, 330),
  ('red', 'Château Montrose', '2ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Estephe', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 2018, 0.75, 450, null, 331),
  ('red', 'Château Montrose', '2ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Estephe', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 1995, 0.75, 950, null, 332),
  ('red', 'Réserve de la Comtesse', null, 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot','Cabernet Franc']::text[], 2019, 0.75, 150, null, 333),
  ('red', 'Réserve de la Comtesse', null, 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot','Cabernet Franc']::text[], 2020, 0.75, 150, null, 334),
  ('red', 'Echo de Lynch Bages', null, 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot']::text[], 2018, 0.75, 125, null, 335),
  ('red', 'Château Grand-Puy-Lacoste', '5ème Grand Cru Classé', 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot']::text[], 2018, 0.75, 195, null, 336),
  ('red', 'Château Grand-Puy-Lacoste', '5ème Grand Cru Classé', 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot']::text[], 2015, 1.5, 410, null, 337),
  ('red', 'Château Grand-Puy-Lacoste', '5ème Grand Cru Classé', 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot']::text[], 2016, 1.5, 410, null, 338),
  ('red', 'Château Lynch Bages', '5ème Grand Cru Classé', 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 2018, 1.5, 590, null, 339),
  ('red', 'Château Lafite Rotschild', '1re Grand Cru Classé', 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot & Petit Verdot']::text[], 1981, 0.75, 1250, null, 340),
  ('red', 'Château Latour', '1re Grand Cru Classé', 'France', 'Bordeaux', 'Pauillac', ARRAY['Cabernet Sauvignon','Merlot & Petit Verdot']::text[], 2005, 0.75, 2000, null, 341),
  ('red', 'Château Branaire-Ducru', '4ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot','Cabernet Franc']::text[], 2020, 0.75, 140, null, 342),
  ('red', 'Château du Glana', 'Cru Bourgeois Supérieur', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc']::text[], 2021, 0.75, 85, null, 343),
  ('red', 'Les Fiefs de Lagrange', null, 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2021, 0.75, 85, null, 344),
  ('red', 'Château Lagrange', '3ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2018, 0.75, 140, null, 345),
  ('red', 'Château Lagrange', '3ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2019, 0.75, 140, null, 346),
  ('red', 'Château Lagrange', '3ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2020, 0.75, 140, null, 347),
  ('red', 'Château Lagrange', '3ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2019, 1.5, 285, null, 348),
  ('red', 'Château Léoville Barton', '2ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot']::text[], 2012, 0.75, 290, null, 349);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('red', 'Château Léoville Poyferré', '2ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 2015, 0.75, 310, null, 350),
  ('red', 'Château Léoville Poyferré', '2ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot','Cabernet Franc']::text[], 2010, 0.75, 390, null, 351),
  ('red', 'Château Léoville Las Cases', '2ème Grand Cru Classé', 'France', 'Bordeaux', 'St-Julien', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc']::text[], 1995, 0.75, 590, null, 352),
  ('red', 'La Dame d''Angludet', null, 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2019, 0.75, 90, null, 353),
  ('red', 'La Dame d''Angludet', null, 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot','Petit Verdot']::text[], 2019, 1.5, 185, null, 354),
  ('red', 'Château Prieuré Lichine', '4ème Grand Cru Classé', 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 2022, 0.75, 130, null, 355),
  ('red', 'Château Kirwan', '3ème Grand Cru Classé', 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 2023, 0.75, 135, null, 356),
  ('red', 'Château d''Issan', '3ème Grand Cru Classé', 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot']::text[], 2019, 0.75, 170, '50% New barrels', 357),
  ('red', 'Château Brane-Cantenac', '2ème Grand Cru Classé', 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Carmenère']::text[], 2018, 0.75, 200, null, 358),
  ('red', 'Château Margaux', '1er Grand Cru Classé', 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc & Petit Verdot']::text[], 2010, 0.75, 1600, null, 359),
  ('red', 'Château Margaux', '1er Grand Cru Classé', 'France', 'Bordeaux', 'Margaux', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc & Petit Verdot']::text[], 1998, 0.75, 1300, null, 360),
  ('red', 'Château La Louviére', null, 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Cabernet Sauvignon','Merlot']::text[], 2019, 0.75, 110, null, 361),
  ('red', 'La Réserve de Malartic', null, 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Merlot','Cabernet Sauvignon','Cabernet Franc']::text[], 2016, 0.75, 100, null, 362),
  ('red', 'Château Malartic Lagravière', null, 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc']::text[], 2020, 0.75, 130, null, 363),
  ('red', 'Domaine De Chevalier', 'Grand Cru Classé', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 2016, 1.5, 520, null, 364),
  ('red', 'Domaine De Chevalier', 'Grand Cru Classé', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Cabernet Sauvignon','Merlot','Cabernet Franc','Petit Verdot']::text[], 2020, 0.75, 260, null, 365),
  ('red', 'Domaine Christophe Billon', 'Côte-Rotie "La Brocarde"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah','Viognier']::text[], 2020, 0.75, 150, 'Côte Brune', 366),
  ('red', 'Domaine Christophe Billon', 'Côte-Rotie "La Brocarde"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah','Viognier']::text[], 2020, 1.5, 300, 'Côte Brune', 367),
  ('red', 'Domaine Jean-Luc Jamet', 'Côte-Rôtie "Terrasses"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2020, 0.75, 180, null, 368),
  ('red', 'Domaine Stéphane Ogier', 'Côte-Rôtie "Mon Village"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2021, 0.75, 160, null, 369),
  ('red', 'Domaine Stéphane Ogier', 'Saint-Joseph "Le Passage"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2021, 0.75, 115, null, 370),
  ('red', 'Domaine Stéphane Ogier', 'Saint-Joseph "Le Passage"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2024, 0.75, 115, null, 371),
  ('red', 'Domaine Jean-Louis Chave', 'Saint-Joseph', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2021, 0.75, 210, null, 372),
  ('red', 'Domaine Jean-Louis Chave', 'Saint-Joseph', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2023, 0.75, 210, null, 373),
  ('red', 'Domaine Jean-Louis Chave', 'Saint-Joseph "Clos Florentin"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2023, 0.75, 485, null, 374),
  ('red', 'Domaine Jean-Louis Chave', 'Hermitage', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2007, 0.75, 650, null, 375),
  ('red', 'Domaine Jean-Louis Chave', 'Hermitage', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2023, 0.75, 650, null, 376),
  ('red', 'Domaine Paul Jaboulet-Ainé', 'Crozes-Hermitage "Domaine de Thalabert"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2017, 0.75, 100, null, 377),
  ('red', 'Domaine Paul Jaboulet-Ainé', 'Hermitage "Maison Bleue"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2017, 0.75, 195, null, 378),
  ('red', 'Domaine Paul Jaboulet-Ainé', 'Hermitage "Maison Bleue"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2022, 0.75, 195, null, 379),
  ('red', 'Domaine Paul Jaboulet-Ainé', 'Hermitage "La Chapelle"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2015, 1.5, 1500, null, 380),
  ('red', 'J.L. Chave Sélection', 'Hermitage "Farconnet" | J.L. Chave Selection', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2020, 0.75, 145, null, 381),
  ('red', 'J.L. Chave Sélection', 'Crozes-Hermitage "Silène"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2023, 0.75, 85, null, 382),
  ('red', 'Domaine Pierre Gaillard', 'Crozes-Hermitage', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2018, 1.5, 140, null, 383),
  ('red', 'Domaine Combier', 'Crozes-Hermitage "Laurent Combier"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2021, 0.75, 75, null, 384),
  ('red', 'Domaine Combier', 'Saint-Joseph', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2021, 0.75, 75, null, 385),
  ('red', 'Domaine Combier', 'Saint-Joseph "Cap Nord"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2023, 0.75, 100, null, 386),
  ('red', 'Domaine August Clape', 'Cornas "Renaissance"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2021, 0.75, 195, null, 387),
  ('red', 'Domaine August Clape', 'Cornas', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2022, 0.75, 285, null, 388),
  ('red', 'Domaine S. Ogier', 'Côtes-du-Rhône "Le Temps Est Venu"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Grenache Noir','Syrah']::text[], 2022, 0.75, 55, null, 389),
  ('red', 'Domaine La Boüissière', 'Vacqueyras "Vieilles Vignes"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Grenache','Syrah','Mourvèdre']::text[], 2023, 0.75, 70, null, 390),
  ('red', 'Domaine La Boüissière', 'Gigondas', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Grenache noir','Syrah']::text[], 2022, 0.75, 80, null, 391),
  ('red', 'Famille Isabel Ferrando', 'Châteauneuf-du-Pape "Réserve August Favier"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Grenache Noir','Syrah','Cinsault','Mourvèdre']::text[], 2020, 0.75, 165, null, 392),
  ('red', 'Clos des Papes', 'Châteauneuf-du-Pape', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Grenache','Mourvèdre','Syrah','Counoise']::text[], 2021, 0.75, 200, null, 393),
  ('red', 'Domaine August Clape', 'Vin des Amis', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2022, 0.75, 80, null, 394),
  ('red', 'Domaine August Clape', 'Côtes-du-Rhône', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2022, 0.75, 100, null, 395),
  ('red', 'Vallée-du-Rhône', 'Côtes-du-Rhône "L''enclave" | Jean-Luc Jamet', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2020, 0.75, 85, null, 396),
  ('red', 'Vallée-du-Rhône', 'Syrah "Valine" | Jean-Luc Jamet', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2020, 0.75, 80, null, 397),
  ('red', 'Domaine S. Ogier', 'Collines Rhodaniennes "La Rosine"', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2020, 0.75, 80, null, 398),
  ('red', 'Château de Fonsalette (Rayas)', 'Syrah Réserve', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Syrah']::text[], 2007, 0.75, 425, null, 399);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('red', 'Château de Fonsalette (Rayas)', 'Côtes-du-Rhône', 'France', 'Bordeaux', 'Pessac-Léognan', ARRAY['Grenache','Cinsault','Syrah']::text[], 2013, 0.75, 350, null, 400),
  ('red', 'Domaine Hauvette', 'Cornaline', 'France', 'Provence', null, ARRAY['Grenache','Syrah','Cabernet Sauvignon']::text[], 2017, 0.75, 120, 'Alpilles | Bio', 401),
  ('red', 'Domaine Hauvette', 'Cornaline', 'France', 'Provence', null, ARRAY['Grenache','Syrah','Cabernet Sauvignon']::text[], 2017, 1.5, 265, 'Alpilles | Bio', 402),
  ('red', 'Domaine Richeaume', 'Tradition', 'France', 'Provence', null, ARRAY['Cabernet Sauvignon','Syrah','Merlot','Carignan']::text[], 2019, 0.75, 65, 'Méditerranée | Bio', 403),
  ('red', 'Château Simone', 'Palette Rouge', 'France', 'Provence', null, ARRAY['Grenache','Mourvèdre','Cinsaut','secondary grape varieties']::text[], 2019, 0.75, 120, 'Palette', 404),
  ('red', 'Château Simone', 'Palette Rouge', 'France', 'Provence', null, ARRAY['Grenache','Mourvèdre','Cinsaut','secondary grape varieties']::text[], 2020, 0.75, 120, 'Palette', 405),
  ('red', 'Domaine de Trévallon', 'Trévallon Rouge', 'France', 'Provence', null, ARRAY['Syrah','Cabernet Sauvignon']::text[], 2019, 0.75, 220, 'Alpilles | Ageing for 24 months in foudres and barrels', 406),
  ('red', 'Domaine de Trévallon', 'Trévallon Rouge', 'France', 'Provence', null, ARRAY['Syrah','Cabernet Sauvignon']::text[], 2015, 0.75, 220, 'Alpilles | Ageing for 24 months in foudres and barrels', 407),
  ('red', 'Domaine Christophe Marin', 'Causseil de Mouillère', 'France', 'Languedoc-Roussillon', null, '{}', 2020, 0.75, 80, null, 408),
  ('red', 'Domaine Christophe Marin', 'Causseil de Mouillère', 'France', 'Roussillon', 'Côtes Catalanes | 100% Grenache Noir | Biodynamic', '{}', 2020, 1.5, 165, null, 409),
  ('red', 'Domaine de Montcalmès', 'Rouge', 'France', 'Roussillon', 'Côtes Catalanes | 100% Grenache Noir | Biodynamic', ARRAY['Syrah','Morvèdre','Grenache']::text[], 2022, 0.75, 110, 'Terrasses du Larzac', 410),
  ('red', 'Azienda Agricola Marion', 'Valpolicella Superiore', 'Italy', 'Veneto', null, ARRAY['Corvina','Rondinella','Molinara','Oseleta']::text[], 2020, 0.75, 80, null, 411),
  ('red', 'Azienda Agricola Marion', 'Valpolicella Superiore', 'Italy', 'Veneto', null, ARRAY['Corvina','Rondinella','Molinara','Oseleta']::text[], 2018, 1.5, 160, null, 412),
  ('red', 'Azienda Agricola Marion', 'Amarone della Valpolicella', 'Italy', 'Veneto', null, ARRAY['Corvina','Corvinone','Rondinella','Molinara 5% Oseleta']::text[], 2020, 0.75, 130, null, 413),
  ('red', 'Amarone della Valpolicella', 'Giuseppe Quintarelli', 'Italy', 'Veneto', null, ARRAY['Corvina','Corvinone','Rondinella','Molinara 5% Oseleta']::text[], 2012, 0.75, 650, null, 414),
  ('red', 'Pietra dei Lupi', 'Cantine Carpentiere', 'Italy', 'Puglia', null, '{}', 2021, 0.75, 60, null, 415),
  ('red', 'Etna Rosso', 'Viticoltori Benanti', 'Italy', 'Sicily', 'Sicily', ARRAY['Nerello Mascalese','Nerello Cappuccio']::text[], 2023, 0.75, 65, 'Volcanic soil', 416),
  ('red', 'Etna Rosso "Serra Della Contessa"', 'Viticoltori Benanti', 'Italy', 'Sicily', 'Sicily', ARRAY['Nerello Mascalese']::text[], 2019, 0.75, 190, 'Volcanic soil | South East facing | 450 meters above sea level', 417),
  ('red', 'Etna Rosso', 'Alta Mora', 'Italy', 'Sicily', 'Sicily', ARRAY['Nerello Mascalese']::text[], 2023, 0.75, 60, 'Volcanic soil', 418),
  ('red', 'Azienda Agricola COS', 'Nero di Lupo', 'Italy', 'Sicily', 'Sicily', ARRAY['Nero d''Avola']::text[], 2022, 0.75, 65, null, 419),
  ('red', 'Barbaresco', 'Produttori del Barbaresco', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2021, 0.75, 110, null, 420),
  ('red', 'Barbera d''Alba Superiore', 'Pira & Figli (Chiara Boscis)', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Barbera']::text[], 2021, 0.75, 75, '12 months ageing in French oak barrels', 421),
  ('red', 'Langhe Nebbiolo', 'Pira & Figli (Chiara Boscis)', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2021, 0.75, 85, null, 422),
  ('red', 'Barolo "Monfalletto"', 'Cordero di Montezemolo', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2020, 0.75, 150, null, 423),
  ('red', 'Barolo "Le Vigne"', 'Luciano Sandrone', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2018, 0.75, 185, null, 424),
  ('red', 'Barolo "Via Nuova"', 'Pira & Figli di Chiara Boscis', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2017, 0.75, 165, '24 months wood ageing', 425),
  ('red', 'Barolo "Le Vigne" Sibi et Paucis', 'Luciano Sandrone', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2014, 0.75, 295, 'Wines kept in the cellar of Sandrone for extra ageing', 426),
  ('red', 'Barbaresco "Gallina"', 'Ugo Lequio', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2018, 0.75, 125, null, 427),
  ('red', 'Barbaresco "Cotta"', 'Sottimano', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2019, 0.75, 175, '24 months barrel ageing, 15% new wood', 428),
  ('red', 'Barbaresco Riserva "Montestefano"', 'Produttori del Barbaresco', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2009, 1.5, 450, null, 429),
  ('red', 'Barbaresco Riserva "Montestefano"', 'Produttori del Barbaresco', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2016, 1.5, 450, null, 430),
  ('red', 'Barbaresco Riserva "Ovello"', 'Produttori del Barbaresco', 'Italy', 'Piedmont', 'Piedmont', ARRAY['Nebbiolo']::text[], 2009, 1.5, 450, null, 431),
  ('red', 'Rosso di Montalcino', 'Siro Pacenti', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2022, 0.75, 80, null, 432),
  ('red', 'Chianti Classico', 'Fontodi', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2021, 0.75, 90, null, 433),
  ('red', 'Chianti Classico Gran Selezione "Vigna del Sorbo"', 'Fontodi', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2020, 0.75, 175, null, 434),
  ('red', 'Flaccianello della Pieve', 'Fontodi', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2020, 0.75, 295, null, 435),
  ('red', 'Brunello di Montalcino', 'Poggio di Sotto', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2016, 0.75, 395, null, 436),
  ('red', 'Brunello di Montalcino', 'Poggio di Sotto', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2017, 0.75, 395, null, 437),
  ('red', 'Brunello di Montalcino', 'Pieve Santa Restituta di Gaja', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2019, 0.75, 175, null, 438),
  ('red', 'Cepparello', 'Isole e Olena', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2013, 0.75, 275, 'Legendary wine', 439),
  ('red', 'Cepparello', 'Isole e Olena', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2014, 0.75, 275, 'Legendary wine', 440),
  ('red', 'Cepparello', 'Isole e Olena', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2015, 0.75, 295, 'Legendary wine', 441),
  ('red', 'Cepparello', 'Isole e Olena', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2016, 0.75, 295, 'Legendary wine', 442),
  ('red', 'Cepparello', 'Isole e Olena', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2017, 0.75, 295, 'Legendary wine', 443),
  ('red', 'Cepparello', 'Isole e Olena', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2018, 0.75, 295, 'Legendary wine', 444),
  ('red', 'Cepparello', 'Isole e Olena', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2020, 0.75, 295, 'Legendary wine', 445),
  ('red', 'Tignanello', 'Marchesi Antinori', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese','Cabernet Sauvignon']::text[], 2021, 0.75, 350, null, 446),
  ('red', 'Ornellaia', null, 'Italy', 'Tuscany', 'Tuscany', ARRAY['Merlot','Cabernet Sauvignon','Cabernet Franc','Petit Verdot']::text[], 2022, 0.75, 450, null, 447),
  ('red', 'Colore', 'Bibi Graetz', 'Italy', 'Tuscany', 'Tuscany', ARRAY['Sangiovese']::text[], 2020, 0.75, 390, '70+ years old vines | Fermentation in open barrique | 20 months ageing | Limited', 448),
  ('red', 'Bodegas Altun', 'Rioja "Coleccion de Parcelas"', 'Spain', 'La Rioja', null, ARRAY['Tempranillo']::text[], 2024, 0.75, 70, '14 months in 225- and 500 litre French oak barrels and concrete vats', 449);

insert into wines (colour, producer, name, country, region, appellation, grapes, vintage, bottle_size, bottle, tasting_note, position) values
  ('red', 'Bodegas Altun', 'Rioja "Villacardiel"', 'Spain', 'La Rioja', null, ARRAY['Tempranillo']::text[], 2023, 0.75, 85, 'Vineyards in Laguardia - 630 m above sea level | Fresh and silky', 450),
  ('red', 'Bodegas Altun', 'Rioja "La Cicatera"', 'Spain', 'La Rioja', null, ARRAY['Garnacha']::text[], 2021, 0.75, 85, 'Very elegant and fruity Rioja', 451),
  ('red', 'Bodegas Lopez de Heredia', 'Viña Tondonia Reserva', 'Spain', 'La Rioja', null, '{}', 2001, 0.75, 190, null, 452),
  ('red', 'Viña Tondonia Reserva', null, 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', '{}', 2006, 1.5, 290, null, 453),
  ('red', 'Viña Tondonia Reserva', null, 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', '{}', 2005, 1.5, 310, null, 454),
  ('red', 'Bodegas Roda', 'Sela', 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', ARRAY['Tempranillo','Garnacha','Graciano']::text[], 2024, 0.75, 65, '12 months wood ageing.', 455),
  ('red', 'Bodegas Roda', 'Sela', 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', ARRAY['Tempranillo','Garnacha','Graciano']::text[], 2019, 1.5, 130, '12 months wood ageing.', 456),
  ('red', 'Bodegas Roda', 'Roda I Reserva', 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', ARRAY['Tempranillo','Graciano']::text[], 2020, 0.75, 160, '16 months wood ageing', 457),
  ('red', 'Bodegas Roda', 'Roda I Reserva', 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', ARRAY['Tempranillo','Graciano']::text[], 2021, 1.5, 365, '16 months wood ageing', 458),
  ('red', 'Bodegas Remirez de Ganuza', 'Fincas de Ganuza Reserva | Remirez de Ganuza', 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', ARRAY['Tempranillo','Graciano','Viura']::text[], 2017, 0.75, 110, null, 459),
  ('red', 'Bodegas Remirez de Ganuza', 'Rioja Reserva | Remirez de Ganuza', 'Spain', 'La Rioja', '75% Tempranillo - 15% Garnacha - 10% Graciano & Mazuelo', ARRAY['Tempranillo','Graciano','Viura & Malvasia']::text[], 2016, 0.75, 175, '28 months wood ageing', 460),
  ('red', 'Alto de la Cruz', 'Alto Horizonte (Aurelio Garcia)', 'Spain', 'Madrid', 'Sierra de Gredos', ARRAY['Garnacha']::text[], 2020, 0.75, 95, 'Vineyards 1150 meters above sea level - very old vines - Finesse!', 461),
  ('red', 'Benje Tinto', 'Envinate', 'Spain', 'Canarias', null, ARRAY['Listán Prieto','Tintilla']::text[], 2022, 0.75, 80, 'Tenerife | Vineyards 1000m above sea level | Fresh and mineral', 462),
  ('red', 'Migan Tinto', 'Envinate', 'Spain', 'Canarias', null, ARRAY['Listàn Negra']::text[], 2021, 0.75, 120, 'Tenerife | Vineyards 800m above sea level | Bucket list wine', 463),
  ('red', 'Viñas Viejas de Soria', 'La Guia', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Albillo (white grape)']::text[], 2020, 0.75, 225, '16 months ageing | only 2000 bottles made', 464),
  ('red', 'Selección', 'Hacienda Solano', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2023, 0.75, 75, 'Very refined style', 465),
  ('red', 'Interpretación', 'Ausàs', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2017, 0.75, 150, 'ex-winemaker Vega Sicilia | Refined power', 466),
  ('red', 'Psi', 'Dominio De Pingus', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Garnacha']::text[], 2023, 0.75, 110, null, 467),
  ('red', 'Flor de Pingus', 'Dominio De Pingus', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2019, 0.75, 250, null, 468),
  ('red', 'Flor de Pingus', 'Dominio De Pingus', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2018, 1.5, 500, null, 469),
  ('red', 'Viña Pedrosa Crianza', 'Hermanos Pérez-Pascuas', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2022, 0.75, 80, null, 470),
  ('red', 'Viña Pedrosa Crianza', 'Hermanos Pérez-Pascuas', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2021, 1.5, 160, null, 471),
  ('red', 'Viña Pedrosa Reserva', 'Hermanos Pérez-Pascuas', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2020, 0.75, 140, null, 472),
  ('red', 'Viña Pedrosa Gran Reserva', 'Hermanos Pérez-Pascuas', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2016, 0.75, 195, null, 473),
  ('red', 'Vega Sicilia', 'Alión', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2021, 0.75, 190, null, 474),
  ('red', 'Vega Sicilia', 'Alión', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino']::text[], 2017, 1.5, 375, null, 475),
  ('red', 'Vega Sicilia', 'Valbuena 5°', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Merlot']::text[], 2020, 0.75, 315, null, 476),
  ('red', 'Vega Sicilia', 'Valbuena 5°', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Merlot']::text[], 2017, 1.5, 690, null, 477),
  ('red', 'Vega Sicilia', 'Valbuena 5°', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Merlot']::text[], 2016, 1.5, 690, null, 478),
  ('red', 'Vega Sicilia', 'Unico', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2005, 0.75, 695, null, 479),
  ('red', 'Vega Sicilia', 'Unico', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2007, 0.75, 695, null, 480),
  ('red', 'Vega Sicilia', 'Unico', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2008, 0.75, 695, null, 481),
  ('red', 'Vega Sicilia', 'Unico', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2011, 0.75, 695, null, 482),
  ('red', 'Vega Sicilia', 'Unico', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2012, 0.75, 695, null, 483),
  ('red', 'Vega Sicilia', 'Unico', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2007, 1.5, 1650, null, 484),
  ('red', 'Vega Sicilia', 'Unico', 'Spain', 'Ribera del Duero', null, ARRAY['Tinto Fino','Cabernet Sauvignon']::text[], 2010, 1.5, 1650, null, 485),
  ('red', 'Vega Sicilia', 'Pintia', 'Spain', 'Ribera del Duero', null, ARRAY['Tinta de Toro']::text[], 2019, 0.75, 175, 'Ageing on French (70%) and American (30%) oak', 486),
  ('red', 'Vega Sicilia', 'Pintia', 'Spain', 'Ribera del Duero', null, ARRAY['Tinta de Toro']::text[], 2021, 0.75, 175, 'Ageing on French (70%) and American (30%) oak', 487),
  ('red', 'Vega Sicilia', 'Pintia', 'Spain', 'Ribera del Duero', null, ARRAY['Tinta de Toro']::text[], 2019, 1.5, 350, 'Ageing on French (70%) and American (30%) oak', 488),
  ('red', 'Vi de Vila Gratallops', 'Alvaro Palacios', 'Spain', 'Catalunya', null, '{}', 2018, 0.75, 120, null, 489),
  ('red', 'Mas d''En Gil', 'Coma Vella', 'Spain', 'Priorat', '80% Garnatxa - 20% Cariñena | Iconic winemaker | Fraicheur', '{}', 2020, 0.75, 95, null, 490),
  ('red', 'Clos Fontà', 'Mas d''En Gil', 'Spain', 'Priorat', '60% Garnatxa - 30% Cariñena - 10% Syrah', '{}', 2017, 0.75, 195, null, 491),
  ('red', 'Pinot Noir "Ernest"', 'Hasher Family Wines', 'South Africa', null, null, ARRAY['Pinot Noir']::text[], 2023, 0.75, 95, 'Hemel-en-Aarde Valley | Burgundy style', 492),
  ('red', 'Pinotage "Batrachella"', 'Hasher Family Wines', 'South Africa', null, null, ARRAY['Pinotage']::text[], 2022, 0.75, 95, 'Hemel-en-Aarde Valley | Super elegant Pinotage', 493),
  ('rose', 'Maison Saint Aix', 'AIX', 'France', null, null, ARRAY['Grenache','Syrah','Cinsault','Mourvèdre']::text[], 2024, 0.75, 70, null, 494),
  ('rose', 'Domaine François Cotat', 'Sancerre | Zeldzaam', 'France', null, null, ARRAY['Pinot Noir']::text[], 2023, 0.75, 125, 'Kimmeridgian soil | No sulfites added during fermentation', 495),
  ('rose', 'Château Saint Maur', 'L''Excellence Cru Classé', 'France', null, null, ARRAY['Grenache','Syrah','Cinsault','Mourvèdre']::text[], 2023, 0.75, 70, null, 496),
  ('rose', 'Domaine des Tours (Rayas)', 'Parisy', 'France', null, null, ARRAY['Grenache','Cinsault']::text[], 2020, 0.75, 110, 'Fantastic & very rare', 497),
  ('sweet', 'Château Vari "Réserve"', 'Monbazillac', 'France', null, null, ARRAY['Semillon','Sauvignon Gris','Muscadelle']::text[], 2001, 0.75, 100, 'South-West | Botrytis', 498),
  ('sweet', 'Château Rieussec', 'Sauternes 1re Grand Cru Classé', 'France', null, null, ARRAY['Sauvignon Blanc','Sémillon','Muscadelle']::text[], 2009, 0.75, 195, 'Sauternes | Botrytis', 499);
